name: mvi
description: "An implementation of the MVI pattern for Flutter"
version: 1.0.0
homepage: https://github.com/devfelipereis/mvi

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  signals: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: