name: mvi
description: "A Flutter package that applies the MVI architectural pattern to help manage app state and logic in a structured and maintainable way."
version: 1.0.6
homepage: https://github.com/devfelipereis/flutter-mvi

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: